### ISSUE TITLE
Investigate Automapper errors in Cacheable object

### ISSUE THREAD

**Issue by Feasoron** [dirigodev/DirigoEdgeCore#20]

**Comment by frxnz** [comment]
Arash thinks this might be related, so I'll put it here instead of creating a new issue.

When I set `IsCacheable` to true in a shortcode, the shortcode only works on first load after an app pool restart. Subsequent loads just show the shortcode like `[homepage_buttons]`. Set `IsCacheable` to false the shortcode loads fine every time.
